package com.badargadh.sahkar.enums;

public enum ExpenseCategory {
	STATIONERY,
    PAYMENT_DEBIT_TO_JAMMAT_BADARGADH,
    PAYMENT_CREDIT_FROM_JAMMAT_BADARGADH,
    MISC,
    JAMMAT_OPENING_BALANCE,
    EXPENSE_OPENING_BALANCE
}
